<?php
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded`
?>
<?php
use Wismolabs\Tracking\Helper\Data as TrackingHelper;

/** @var \Wismolabs\Tracking\Helper\Data $helper */
$helper = $this->helper(TrackingHelper::class);
?>
<?php /** @var  $block \Magento\Shipping\Block\Items */ ?>
<?php  $_order = $block->getOrder() ?>

<?php if ($helper->isLinkEnabledInUserAccountOrdersPage($_order->getStoreId())): ?>
<div class="actions-toolbar">

    <?php if ($helper->isLinkEnabledInUserAccountOrdersPage($_order->getStoreId()) &&
         $_order->getTracksCollection()->count()): ?>
        <?php $allShipmentsUrl = $helper->getCombinedUrl($_order) ?>
        <a href="#" class="action track" title="<?= $escaper->escapeHtml(__('Track All Shipments')) ?>"
           data-mage-init='{"popupWindow": {
                "windowURL":"<?= $escaper->escapeHtml($allShipmentsUrl); ?>",
                "windowName":"trackorder",
                "width":800,
                "height":600,
                "left":0,
                "top":0,
                "resizable":1,
                "scrollbars":1
            }}'>
            <span><?= $escaper->escapeHtml(__('Track All Shipments'))  ?></span>
        </a>
    <?php endif; ?>
    <a href="<?= $escaper->escapeUrl($block->getPrintAllShipmentsUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $escaper->escapeHtml(__('Print All Shipments')) ?></span>
    </a>
</div>
    <?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
    <div class="order-title">
        <strong>
            <?= $escaper->escapeHtml(__('Shipment #')) ?>
            <?= $escaper->escapeHtml($_shipment->getIncrementId()) ?>
        </strong>
        <a href="<?= $escaper->escapeUrl($block->getPrintShipmentUrl($_shipment)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $escaper->escapeHtml(__('Print Shipment')) ?></span>
        </a>
        <?php
        $thisShipmentUrl = $helper->getCombinedUrl($_order, $_shipment->getTracksCollection())
        ?>
        <?php if ($helper->isLinkEnabledInUserAccountOrdersPage($_order->getStoreId())): ?>
        <a href="#"
           data-mage-init='{"popupWindow": {
           "windowURL":"<?= $escaper->escapeHtml($thisShipmentUrl); ?>",
           "windowName":"trackshipment",
           "width":800,
           "height":600,
           "top":0,
           "left":0,
           "resizable":1,
           "scrollbars":1
           }}'
           title="<?= $escaper->escapeHtmlAttr(__('Track this shipment')) ?>"
           class="action track">
            <span><?= $escaper->escapeHtml(__('Track this shipment')) ?></span>
        </a>
        <?php endif; ?>
    </div>
        <?php $tracks = $_shipment->getTracksCollection(); ?>
        <?php  if ($tracks->count() && $helper->isLinkEnabledInUserAccountOrdersPage($_order->getStoreId())): ?>
        <dl class="order-tracking" id="my-tracking-table-<?= (int) $_shipment->getId() ?>">
            <dt class="tracking-title">
                <?= $escaper->escapeHtml(__('Tracking Number(s):')) ?>
            </dt>
            <dd class="tracking-content">
                <?php
                $i = 1;
                $_size = $tracks->count();
                foreach ($tracks as $track): ?>
                    <?php if ($track->isCustom()): ?>
                        <?= $escaper->escapeHtml($track->getNumber()) ?>
                    <?php else: ?>
                        <?php
                           $url = $helper->getUrl($_order, $track) ?>
                            <a href="#"
                                data-mage-init='{"popupWindow": {
                                "windowURL":"<?= $escaper->escapeUrl($url) ?>",
                                "windowName":"trackorder",
                                "width":800,
                                "height":600,
                                "left":0,
                                "top":0,
                                "resizable":1,
                                "scrollbars":1
                                }}'
                                class="action track">
                                <span><?= $escaper->escapeHtml($track->getNumber()) ?></span>
                            </a>
                    <?php endif; ?>
                    <?php if ($i != $_size): ?>, <?php endif; ?>
                    <?php $i++;
                endforeach; ?>
            </dd>
        </dl>
    <?php  endif; ?>
    <div class="table-wrapper order-items-shipment">
        <table class="data table table-order-items shipment" id="my-shipment-table-<?= (int) $_shipment->getId() ?>">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Items Shipped')) ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                    <th class="col qty"><?= $escaper->escapeHtml(__('Qty Shipped')) ?></th>
                </tr>
            </thead>
                <?php $_items = $_shipment->getAllItems(); ?>
                <?php foreach ($_items as $_item): ?>
                    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
        <?= $block->getCommentsHtml($_shipment) ?>
    <?php endforeach; ?>

<?php else: ?>
    <?=  $block->setTemplate("Magento_Shipping::items.phtml")->toHtml();
    ?>
<?php endif; ?>
